<!DOCTYPE html>
<html lang="az">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sadə Sayt</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            background-color: #f4f4f4;
        }
        .header {
            background-color: #4CAF50;
            color: white;
            padding: 20px;
            font-size: 24px;
            margin-bottom: 20px;
        }
        .message {
            font-size: 20px;
            color: #333;
        }
    </style>
</head>
<body>
    <div class="header">
        Salam hörmətli istifadəçilər
    </div>

    <div class="message">
        İxtisas seçimi üçün bizə yazın: 0507793661
    </div>
</body>
</html>
